[dotfiles]
"~/.local/bin" = { mode = "symlink-each" }
"~/.config/mise/conf.d" = { mode = "symlink-each" }
"~/.config/atuin/config.toml" = {}
"~/.zprofile/zsh" = { block = """
export XDG_CACHE_HOME=~/.cache
export XDG_CONFIG_HOME=~/.config
export XDG_DATA_HOME=~/.local/share
export XDG_STATE_HOME=~/.local/state

source <(~/.local/bin/mise activate zsh --shims)
""" }
"~/.zshrc/zsh" = { block = """
source <(~/.local/bin/mise activate zsh)

fpath=(~/.local/share/zsh-completions/src ~/.local/share/zsh/site-functions $fpath)
autoload -Uz compinit
compinit

source ~/.local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source <(atuin init zsh --disable-up-arrow)
source <(starship init zsh)
source <(zoxide init zsh)
""" }
"~/Library/Application Support/Code/User/settings.json" = {}
