[dotfiles]
"~/.local/bin" = { mode = "symlink-each" }
"~/.config/mise/conf.d" = { mode = "symlink-each" }
"~/.config/mise/config.toml/mise" = { block = "" }
"~/.config/atuin/config.toml" = {}
"~/.zprofile/zsh" = { block = "source <(~/.local/bin/mise activate zsh --shims)" }
"~/.zshrc/zsh" = { block = """
source <(~/.local/bin/mise activate zsh)

fpath=(~/.local/share/zsh-completions/src ~/.local/share/zsh/site-functions $fpath)
autoload -Uz compinit
compinit

source ~/.local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

source <(starship init zsh)
source <(zoxide init zsh)
source <(atuin init zsh --disable-up-arrow)
""" }
"~/Library/Application Support/Code/User/settings.json" = {}
