[dotfiles]
"~/.config/mise/conf.d" = { mode = "symlink-each" }
"~/.zshrc/activate" = { block = "source <(~/.local/bin/mise activate zsh)" }
"~/.zshrc/zsh" = { block = """
fpath=(~/.local/share/zsh-completions/src ~/.local/share/zsh/site-functions $fpath)

autoload -Uz compinit
compinit

source ~/.local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

source <(starship init zsh)
source <(zoxide init zsh)
source <(atuin init zsh --disable-up-arrow)
""" }
"~/.zprofile/activate" = { block = "source <(~/.local/bin/mise activate zsh --shims)" }
"~/.local/bin" = { mode = "symlink-each" }
"~/Library/Application Support/Code/User/settings.json" = {}
"~/.config/atuin/config.toml" = {}
