[tools]
1password-cli = "latest"
atuin = "latest"
aube = "latest"
bun = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
helix = "latest"
node = "latest"
opencode = "latest"
oxfmt = "latest"
oxlint = "latest"
pi = "latest"
pitchfork = "latest"
pnpm = "latest"
python = "latest"
rg = "latest"
ruby = "latest"
ruff = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
tombi = "latest"
ty = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
zig = "latest"
zls = "latest"
zoxide = "latest"
