[settings]
minimum_release_age_excludes = ["opencode"]

[settings.python]
compile = false

[settings.ruby]
compile = false

[tools]
aube = "latest"
bun = "latest"
fd = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
helix = "latest"
java = "temurin"
node = "latest"
opencode = "latest"
oxfmt = "latest"
oxlint = "latest"
"pipx:httpie" = "latest"
pitchfork = "latest"
pkl = "latest"
pnpm = "latest"
python = "latest"
rg = "latest"
ruby = "4.0.5"
ruff = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
tombi = "latest"
ty = "latest"
uv = "latest"
yq = "latest"
zig = "latest"
zls = "latest"
