[settings]
minimum_release_age_excludes = ["opencode"]

[settings.dotfiles]
root = "~/Workspaces/xqm32/dotfiles"

[settings.python]
compile = false

[settings.ruby]
compile = false

[bootstrap.repos]
"~/Workspaces/xqm32/dotfiles" = { url = "https://github.com/xqm32/dotfiles" }
"~/Workspaces/github/zsh-completions" = { url = "https://github.com/zsh-users/zsh-completions" }
"~/Workspaces/github/zsh-syntax-highlighting" = { url = "https://github.com/zsh-users/zsh-syntax-highlighting" }
"~/Workspaces/github/zsh-autosuggestions" = { url = "https://github.com/zsh-users/zsh-autosuggestions" }

[dotfiles]
"~/.config/mise/config.toml" = {}
"~/.zshrc/source" = { block = "source ~/Workspaces/xqm32/dotfiles/.zshrc" }
"~/.zprofile/source" = { block = "source ~/Workspaces/xqm32/dotfiles/.zprofile" }

[tools]
aube = "latest"
bun = "latest"
eza = "latest"
fd = "latest"
go = "latest"
"go:golang.org/x/tools/gopls" = "latest"
golangci-lint = "latest"
helix = "latest"
node = "latest"
opencode = "latest"
oxfmt = "latest"
oxlint = "latest"
"pipx:httpie" = "latest"
pitchfork = "latest"
pnpm = "latest"
python = "latest"
rg = "latest"
ruby = "4.0.5"
ruff = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
tombi = "latest"
ty = "latest"
uv = "latest"
yq = "latest"
zig = "latest"
zls = "latest"
fzf = "latest"
gh = "latest"
starship = "latest"
zoxide = "latest"
1password-cli = "latest"
